# Generated by Django 5.2 on 2025-05-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_client_employee_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_firstname', models.CharField(max_length=50, verbose_name='Фамилия покупателя')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('buyer_surname', models.CharField(max_length=50, verbose_name='Отчество покупателя')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='комментарий к заказу')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Вывоз из магазина'), ('CR', 'Доставка курьером'), ('PP', 'Пункт выдачт заказов')], default='SH', max_length=2, verbose_name='способо доставки')),
                ('daet_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.equipment', verbose_name='Снаряжение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='equipment',
            field=models.ManyToManyField(through='shop.Pos_order', to='shop.equipment', verbose_name='Товар'),
        ),
    ]
